# SwiftLint configuration for RAWG.IO
# https://github.com/realm/SwiftLint

# Paths to exclude from linting
excluded:
  - Tuist/.build
  - Derived
  - DerivedData
  - .build
  - "*.generated.swift"

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - nesting

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - to
    - ok
    - or
    - on

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

force_unwrapping:
  severity: warning

implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets

# Custom rules
custom_rules:
  no_print_statement:
    name: "No print() statements"
    regex: "^(?!\\s*///).*\\bprint\\s*\\("
    message: "Use Logger instead of print() for production code"
    severity: warning
    
  no_direct_dispatch:
    name: "No direct DispatchQueue usage"
    regex: "DispatchQueue\\.(main|global)"
    message: "Use async/await instead of DispatchQueue for concurrency"
    severity: warning

# Reporter type
reporter: "xcode"
